<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Odyssey.User.Application\Odyssey.User.Application.csproj" />
      <ProjectReference Include="..\Odyssey.User.Domain\Odyssey.User.Domain.csproj" />
    </ItemGroup>

</Project>
